#pragma once
#include <wx/app.h>
#include <wx/button.h>
#include <wx/clipbrd.h>
#include <wx/colour.h>
#include <wx/dialog.h>
#include <wx/filedlg.h>
#include <wx/font.h>
#include <wx/frame.h>
#include <wx/gbsizer.h>
#include <wx/menu.h>
#include <wx/msgdlg.h>
#include <wx/panel.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statusbr.h>
#include <wx/string.h>
#include <wx/textctrl.h>
#include <wx/textfile.h>

#include <array>
#include <cstdint>
#include <map>
#include <optional>
#include <random>
#include <type_traits>
#include <vector>

#include "Forward.h"
#include "Constants.h"
